### ISSUE TITLE
Dark Link still appears without having his soul

### ISSUE THREAD

**Issue by JustAMosquito** [rrealmuto/OoT-Randomizer#100]
I'm playing a seed with Shuffle Enemy Souls and Shuffle Enemy Drops (link to the seed : https://ootrandomizer.com/seed/get?id=1609982), and the issue is that I can still fight Dark Link and get his item despite not having his soul. However, after I defeated him, the door to the river doesn't open. Here's a video to see for yourself

https://github.com/rrealmuto/OoT-Randomizer/assets/109001790/23c43d6b-a5a9-4c93-984f-c76273bc21c7

**Comment by rrealmuto** [comment]
Seems like I accidentally deleted the hack that made dark link work when I last rebased enemy soul shuffle...
