### ISSUE TITLE
More incorrect logics

### ISSUE THREAD

**Issue by JustAMosquito** [rrealmuto/OoT-Randomizer#101]
After finishing my most recent seed, I found more incoherences/bugs with the current logic :

1. "Bottom of the Well Basement Redead Near Chest" is missing the requirements to go through one of the 2 boulders blocking the way (same logic as "Bottom of the Well Map Chest")

2. "ZF Adult Hidden Caves Skulltula 1 to 5" should be in the "ZF Hidden Cave" region

3. Following the previous point, "ZF Hidden Cave" exit from "Zoras Fountain" region should have the boulder logic instead of just _can_use(Silver_Gauntlets) and can_blast_or_smash_

4. In Spirit Temple MQ, "Adult Spirit Temple" to "Lower Adult Spirit Temple" is missing _has_soul(Wallmaster) and has_soul(Stalfos)_. Thus, "Spirit Temple MQ Adult Climb Wallmaster 1 to 4" should be moved to the "Adult Spirit Temple" region and their logic should be _"has_soul(Wallmaster) and ((can_use(Fire_Arrows) or (logic_spirit_mq_lower_adult and can_use(Dins_Fire))))"_ and also "Mirror_Shield" for the 3 that spawn by mirror shielding the suns (the 4th one spawns by just entering the room).
**This point is for saying that you need to defeat both Stalfoses and Wallmasters to open the gate and access the "Lower Adult Spirit Temple" region, but you don't need to open the gate in order to defeat them.**

5. "Gerudo Training Ground MQ Dinolfos Chest" doesn't have an age check but all the enemies have _is_adult_. This way means that you can get the chest as child but not kill the enemies that spawns it... So I guess either add the logic for child for the enemies or add _is_adult_ for the chest.

6. In GTG MQ, "Gerudo Training Ground Lava Room Front" is missing an access to "Gerudo Training Ground Lava Room Door".
Another method I thought is to just delete the "Gerudo Training Ground Lava Room Door" region and replace all the bubbles in their corresponding region.
**This point is for saying that you can kill the bubbles by coming from the "Gerudo Training Ground Back Areas" region.**

7. There are 2 grasses missing in Dodongo's Cavern MQ : one in "Dodongos Cavern Torch Puzzle Lower" (near the door to "Dodongos Cavern Larvae Room") and one in "Dodongos Cavern Before Upper Lizalfos"

Sorry for the long post, I hope you can comprehend everything I've said. Also, the solutions I proposed are just what I thought to be correct. But feel free to correct me or make other solutions if you find better ones.
Here's the link to the seed that made me make this list (in case you need it) : https://ootrandomizer.com/seed/get?id=1609982

**Comment by rrealmuto** [comment]
These should all be fixed now except the DC grass. Pretty sure those don't spawn unless "Fix broken actors" is enabled. They will eventually be shuffled
