### ISSUE TITLE
Incorrect logics

### ISSUE THREAD

**Issue by JustAMosquito** [rrealmuto/OoT-Randomizer#102]
Back again with more enemies, boulders and pots logics that may need correction.

1. _Water Temple Before Compass Chest Stingrays_ 1 to 4 only spawn when the water is at the top level, meaning that you need Iron Boots and Hookshot. You cannot bypass that with Zelda's Lullaby.
2. _Water Temple South Basement Shell Blade_ and _Water Temple Dragon Statue Shell Blade_ 1 and 2 are missing _Iron_Boots_ and _Hookshot_. I don't think there's another way to defeat them underwater.
3. _Spirit Temple MQ Silver Block Hallway Chest_ must have the logic to pass the boulder instead of just _has_bombchus_. That or relocate this check to the _Spirit Temple Shared_ region and remove _has_bombchus_
4. With **Shuffle Empty Pots** on (I think that's the setting that's causing this), the pots in DMC can be obtainable as child. But their logic is only _is_adult_. So maybe either make those pots no more collectable as child, or add the logic if this setting is active (if it's possible)

The next points are some improvements/additions to some checks. Their logics aren't wrong as of now but there can be other ways to get their check.

5. _Ganons Castle MQ Shadow Trial Beamos 1_ must be in the _Ganons Castle Shadow Trial Moving Platform_ region and 2 to 4 must be in the _Ganons Castle Shadow Trial Second Gap_ region instead of just the _Ganons Castle Shadow Trial_ region. Their logic should then just be _can_kill_beamos_
6. Both _Ganons Castle Shadow Trial Bubble_ and _Ganons Castle Shadow Trial Like Like_ can be killed as child with Slingshot from the entrance. This could also apply to _Ganons Castle MQ Shadow Trial Bubble_, but since the requirement to access the Shadow Trial region is _is_adult_, it would mean to change this logic to _True_ and add is_adult to the other checks in _Ganons Castle Shadow Trial_ and the exit to _Ganons Castle Shadow Trial Moving Platform_ logics. Your call for that

I hope everything is clear enough. As always, don't hesitate to ask for clarification or just to correct me.

**Comment by JustAMosquito** [comment]
Another one I just saw in my current seed :

_Spirit Temple MQ Lobby_ to _Adult Spirit Temple_ needs the boulder logic instead of just _has_bombchus_, unless this boulder in particular isn't randomized due to the fact that it has to only be brown to access the shared region.

**Comment by JustAMosquito** [comment]
Last one I found while finishing my current seed : 

_Jabu Jabus Belly MQ Main_ to _Jabu Jabus Belly Invisible Enemies Room_ should have _Jabu Jabus Belly Parasitic Tentacle Cleared_ instead of _(at('Jabu Jabus Belly Depths', has_soul(Jabu_Jabu_Tentacle))_. The parasitic tentacle is blocking this entrance. And if the boulders blocking the swicth and the entrance to defeat this tentacle aren't passable as child, there is no way to enter the invisible enemies room.

**Comment by rrealmuto** [comment]
The boulder on the ceiling in MQ Spirit is forced to stay a brown boulder so the two comments about that aren't a problem. I'll go ahead and fix the others as you've suggested. Thanks for the input as always.

**Comment by JustAMosquito** [comment]
Sorry for the confusion, but for the _Spirit Temple MQ Silver Block Hallway Chest_, I wasn't talking about the boulder on the ceiling, but the boulder between the Child Beginning region and the Child Climb region (see the picture below). You need to hit the eye-switch as child for the chest to appear, and for that child has to pass this boulder to reach the hallway. So the logic for this check should have the same boulder logic as the _Spirit Temple shared_ exit from _Child Spirit Temple_

![image](https://github.com/rrealmuto/OoT-Randomizer/assets/109001790/44339426-e04f-45aa-befb-bc3686aec595)

If I'm still wrong, sorry for that, but that's how I understand it.

And thank you for clarifying the logic for the ceiling boulder. That's good to know that it'll always be brown

**Comment by rrealmuto** [comment]
I gotcha. Just shows how much I know about MQ :)

**Comment by rrealmuto** [comment]
These should all be fixed now

**Comment by JustAMosquito** [comment]
Thank you for fixing them. However, I noticed that the JJB MQ issue I posted (https://github.com/rrealmuto/OoT-Randomizer/issues/102#issuecomment-2075313167) wasn't corrected. Is it because I was wrong with my reasoning or is it just an oversight on your part ?

**Comment by rrealmuto** [comment]
Just missed it

**Comment by r0bd0g** [comment]
What you spotted in MQ Spirit with the silver block hallway chest applies to main branch. There's a trick to hammer the boulder as adult so that child could pass through without bombchus, that's not currently being made use of for that chest. You did end up fixing that on this branch.
