### ISSUE TITLE
Boulder Shuffle/Enemy drop logic problem - Fountain hidden cave

### ISSUE THREAD

**Issue by Toffile360** [rrealmuto/OoT-Randomizer#108]
Fountain hidden cave enemies only show up as an adult and while the region can be accessed as a child if boulder shuffle is on, nothing will spawn there and an unbeatable seed can be generated. (See https://ootrandomizer.com/seed/get?id=1706371 for example seed)

**Comment by rrealmuto** [comment]
fixed
