### ISSUE TITLE
Shadow Temple Logic Issues

### ISSUE THREAD

**Issue by JustAMosquito** [rrealmuto/OoT-Randomizer#109]
I found more issues with the current logic, most of them being in Shadow Temple (V and MQ) with _Dungeon Boss Shortcuts_ and _Shuffle Enemy Souls_. It's sometimes difficult to explain clearly, so I hope you can understand.

1. In MQ, the logic for the enemies listed in the _"Shadow Temple Upper Huge Pit"_ region should have this code added to their _"can_kill"_ logic : 
      `"not shadow_temple_shortcuts or (Small_Key_Shadow_Temple, 6) or ((logic_lens_shadow_mq_platform or can_use(Lens_of_Truth)) and Hover_Boots)"`
In the current logic, if we have 5 keys and use them to unlock all doors except the one leading directly to _"Shadow Temple Upper Huge Pit"_ (meaning we go through the _Wind Tunnel_ with Shortcuts ON) , we cannot have access to these enemies without _Hover Boots_ nor the Lens requirement to cross the pit. With this code, it garanties us to have access from both entrances with their requirements and without running out of keys.
Another idea to solve this issue is to create a new region for these enemies, like this :
![image](https://github.com/user-attachments/assets/c72ce937-c995-4ef2-9770-4336241600d2)

2. I couldn't verify this one in my most recent seed, but I think that in Vanilla, you cannot jump the gap (see picture below) to get back to the "Skulltula Hallway" from the Huge Pit (there is no Longshot target and I don't think you can hookshot the guillotines). Meaning that the 4 Skulltulas and the Wallmaster (and maybe even the Bubble) should have this logic added : 
`not shadow_temple_shortcuts or (Small_Key_Shadow_Temple, 5)`.
![image](https://github.com/user-attachments/assets/90bf3b5c-b7ce-4c5b-9c4e-3c39438170f6)
If there exist a way to cross the gap that is in logic, then you can forget about this point.

3. _"Shadow Temple MQ Huge Pit Lower Beamos"_ should be placed in the _"Shadow Temple Falling Spikes"_ region, to guarantee its access from both sides with enough keys.

4.  This one I could be wrong, but I think the exit _"Shadow Temple Wind Tunnel"_ from _"Shadow Temple Invisible Spikes"_ should be :
`"((has_soul(Redead_and_Gibdo) and Hookshot) or Longshot) and (Small_Key_Shadow_Temple, 3)"`
I don't think you can hookshot the nearest target to the door without standing on the chest from the redeads (at least I couldn't do it). The only other way I think to do so would be to hover from the back left platform to the door, but I don't know if it is considered as "in logic" or not. This should apply for both V and MQ.

5. _"Shadow Temple MQ Shortcut Skulltula"_ should be placed in the _"Shadow Temple First Beamos"_ region, since it's near the invisible chest even with Shortcuts OFF,

6. "Shadow Temple MQ Before Boat Skullwalltula" should have _Longshot_ or _Bow_ to be sure we can kill it if Shortcuts are ON.

I really hope that everything is clear enough for you to understand. I had some trouble to really understand the Shadow logic so don't hesitate to correct me if I'm still wrong or if you need me to clarify my ideas

**Comment by JustAMosquito** [comment]
After finishing another seed, I found another logic issue in Shadow Temple : 
"Shadow Temple MQ Spike Wall Skulltulas" need to have _can_use(Dins_Fire)_. I'm pretty sure you cannot kill them without burning the spike walls. Since the Keeses spawn near the door, there's no need to adapt their logic

**Comment by rrealmuto** [comment]
I should've closed this issue a while ago since it's all since been fixed. 

Regarding your new issue w/ the spike wall skulltulas: I think you can kill them w/ bow or hookshot too but it's nonetheless still a logic issue
