### ISSUE TITLE
Game doesn't boot up on wii vc and ED on glitch logic (v6.2.76)

### ISSUE THREAD

**Issue by ETR-BTF** [rrealmuto/OoT-Randomizer#35]
It does load on pj64, but not on wii vc or everdrive. ~~The easiest fix would be to disable those settings in the gui when glitch logic is enabled, just like how MQ dungeons and ER are disabled.~~

What happens is that the screen remains black after you press a button on the title screen. On pj64 I was able to load Link's house.

Edit: yellow bar on everdrive

**Comment by rrealmuto** [comment]
Any idea what's so different about glitched logic that would cause the game to not load? I do intend on disabling the setting, under glitched logic, but nonetheless the game should still work. 

Does glitched settings without pots/crates on my branch cause the same issue?

**Comment by ETR-BTF** [comment]
I rolled a seed with the s5 preset + glitch logic and that indeed causes the same issue on wii vc. I have no clue what is causing this.

This is the seed I just tested: https://ootrandomizer.com/seed/get?id=1103539

Edit: just to confirm I rerolled the seed but with glitchless logic instead and it loads fine. https://ootrandomizer.com/seed/get?id=1103543

**Comment by ETR-BTF** [comment]
Dusk looked at the crash handler: https://discord.com/channels/274180765816848384/438698093354156032/979728356679499826

**Comment by ETR-BTF** [comment]
No crash when rolling on v6.2.72 of the main dev branch.

**Comment by rrealmuto** [comment]
Would you be able to try making a seed using this branch? I think I know what's going on.

https://github.com/rrealmuto/OoT-Randomizer/tree/35-game-doesnt-boot-up-on-wii-vc-and-ed-on-glitch-logic-v6276

**Comment by ETR-BTF** [comment]
Loaded s5 preset -> changed to glitch logic and rolled a seed. I was able to load the seed on wii vc and run around in Kokiri Forest just fine. Need anything else tested?
