### ISSUE TITLE
Master sword on B as child

### ISSUE THREAD

**Issue by coavins** [rrealmuto/OoT-Randomizer#45]
After changing age to child midway through a playthrough, suddenly P1 had Master sword on B. Pressing B uses the kokiri sword. P1 hasn't found the kokiri sword yet. This wasn't the first time changing to child age.

2 player multiworld using bizhawk-coop script.

Not sure if this issue belongs in here or the upstream, but we were playing on this branch: https://ootrandomizer.com/generatorDev?version=devrreal_

`Generation Date 7/11/2022, 2:29:13 AM UTC --Seed 9J6P4BYJKN -- Settings String DSAKMFQNALH2EAASC8WFSH244HLRFQ49XXCHGATL62ANAACCAAEACABNAE2BVAFSTQ3U2WGB4SQWASFBAA2JMAJZLKSEC`

**Comment by rrealmuto** [comment]
Closing as this is a known issue with the randomizer
