### ISSUE TITLE
game crashes

### ISSUE THREAD

**Issue by Gorodine** [rrealmuto/OoT-Randomizer#79]
i rolled a hellmode, spawned at the fortress and killed the top skulltula near the chest.
It had a silver rupee that instantly made me crashes.

Not the first time that my game crashed because of a freestanding showing up on my screen, but until now i've never known what caused it. Now i figured out how but not why.

Here is the seed : https://ootrandomizer.com/seed/get?id=1456133

**Comment by rrealmuto** [comment]
What do you play on? I just went and killed the skulltula and it doesn't seem to crash.

![GLideN64_THE_LEGEND_OF_ZELDA_013](https://github.com/rrealmuto/OoT-Randomizer/assets/5086838/842824c8-6e9a-4db7-a854-2e64b66129de)

**Comment by Gorodine** [comment]
yeah it's my fault. I used an old offline generator to patch my seed. (for the custome musics)

I tried again with yours and it worked perfectly, sorry :S

**Comment by rrealmuto** [comment]
No problem. Glad you figured it out! The custom music system was updated recently so you have to patch with newer versions.
