### ISSUE TITLE
Water Temple MQ wonderitems logic incorrect

### ISSUE THREAD

**Issue by JustAMosquito** [rrealmuto/OoT-Randomizer#84]
Hi. In my last seed, I was stuck because the game intended me to get "Water Temple MQ Dragon Statue Eyes Hookshot Wonderitem 1" without having the "Dark Link Soul". After looking at the logic file, I found out that it's because this check and the 2nd eye wonderitem are placed in the wrong region. They should be in the "Water Temple Dragon Statue" region instead of "Water Temple Dark Link Region". Here's the link to my seed in case you need it out : https://ootrandomizer.com/seed/get?id=1483204

**Comment by rrealmuto** [comment]
Alright thanks for letting me know. I'll get it resolved soon.

**Comment by JustAMosquito** [comment]
Also, I noticed something else that kept me locked. In GTG MQ, the requirements for leaving "Gerudo Training Ground Stalfos Room" to "Gerudo Training Ground Back Areas" doesn't have the "Stalfos Soul" and "Skulltula Soul", but we need to defeat both Stalfos and Skulltulas to exit the room. So right now the game expect me to get to the lava room from the left side without having the Soul of Skulltula.

**Comment by rrealmuto** [comment]
thanks I confirmed both of these and have already started working on fixes.

However I am currently in a bit of a freeze on pushing any changes to my fork. I'm working on incorporating a long overdue modification to the potsanity system as detailed in https://github.com/OoTRandomizer/OoT-Randomizer/pull/2069

These logic changes will be incorporated with that in hopefully the next few days.

**Comment by rrealmuto** [comment]
and I'll probably introduce 100 new ones :)

**Comment by JustAMosquito** [comment]
Oh wow, I just looked at it and it looks great, I'm excited to test these new settings. Best of luck with that :)
