### ISSUE TITLE
Spirit Temple MQ Child: After defeating the Torch Slugs, doors don't open

### ISSUE THREAD

**Issue by InfiniteRizard** [rrealmuto/OoT-Randomizer#87]
For some reason after defeating the Torch Slugs in Spirit MQ as child, don't open the doors on the left and right, locking me out of finishing the rando.

I think it is connected to Boss Souls and the trigger being funky.

For better testing, here is the spoiler log. Hope it isn't my mistake in some way xD

[OoT_7D867_WADB2ILXVT_Spoiler.json](https://github.com/rrealmuto/OoT-Randomizer/files/13539978/OoT_7D867_WADB2ILXVT_Spoiler.json)

**Comment by rrealmuto** [comment]
If you by chance have keese souls accessible, that would fix the problem. Turns out there are supposed to be keese in that room that don't spawn, however the soul shuffle hack sees them and doesn't consider the room cleared because of it. I'll look into fixing that

**Comment by InfiniteRizard** [comment]
Yeah then the seed is currently unbeatable, cause the keese soul is in water and iron boots in fire. My hammer is behind the looked doors in spirit xD

I look forward when it is fixed, want to do an all settings rando with my friends then.
