### ISSUE TITLE
Minor Location specific issues with shuffle Grass and Suffle Enemy Drops

### ISSUE THREAD

**Issue by 3pacgangstarap** [rrealmuto/OoT-Randomizer#90]
Location List and Item Pool are both claiming there are 5 grass in this room, but in game i'm only seeing 3 render. All I know for sure is that this one here is _not_ the broken one

`("Deku Tree MQ Basement Back Room Grass 3",                      ("Grass",        0x0,   (8,0,5), None,                         'Rupees (5)',                            ("Deku Tree MQ", "Master Quest", "Grass",))),`

but any of the two on either side of that in the locationlist could be the broken ones. have not confirmed yet if the problem is consistent. but there were 3 grass showing up, two not, and number 3 is the only one i could confirm as one of them that showed up

**Comment by rrealmuto** [comment]
The heck grass doing down there?

![image](https://github.com/rrealmuto/OoT-Randomizer/assets/5086838/c1a2aea3-55d0-417d-8389-cf92153a5a7a)

**Comment by 3pacgangstarap** [comment]
that's pretty funny. i just confirmed that even in the 3ds remake of master quest only 3 grass spawn. wonder if you could still break those somehow if you got out of bounds

**Comment by 3pacgangstarap** [comment]
while i was looking at this i also noticed there's a scrub in MQ in the "larva room" that doesn't drop anything if enemy drops are enabled. same room has a single keese and 8 gohma larva. i don't have a proper master quest rom i can open to look up the memory address of the scrub

**Comment by 3pacgangstarap** [comment]
I don't know that it might be worth creating a separate issue at this point, but I keep finding little things. 
![With this Bubble enemy](https://github.com/rrealmuto/OoT-Randomizer/assets/3536952/5e2fccb8-4ab5-41aa-b3cf-4c12f11fe146)

when you have enemy drops enabled the other 4 bubbles in the area generate a little sparkle effect like a hidden wonderitem. but this one either generates it's effect too low to be able to see or not at all. because of this I thought the enemy wasn't spawning in at all and had to confirm in the editor where it was. to kill it you have to jump slash on top of it and you'll collect the item pretty much at the same time you void out.

so without that little sparkle effect telling you where it is it becomes really difficult to find that check in enemy drop shuffle. dunno what a fix for that would look like

**Comment by 3pacgangstarap** [comment]
actually looking at it again, i don't think that Bubble actually gets shuffled. there's a reference to it in the LocationList but the location doesn't show up in the spoiler log for my seed and there's no reference to it in the overworld logic json. is that just because it isn't considered in logic or is there some other reason it's being left out of the spoiler log. i thought it gave me an item when i killed it but it was hard to tell since i voided out at nearly the same time. is this a case of it not being shuffled intentionally for whatever reason? perhaps the difficulty in getting it to spawn/killing it? i dunno, anyway hope you find this helpful somehow

**Comment by rrealmuto** [comment]
That bubble is unshuffled because I have never been able to actually kill it. If you know a way to do so, I would shuffle it

**Comment by rrealmuto** [comment]
> that's pretty funny. i just confirmed that even in the 3ds remake of master quest only 3 grass spawn. wonder if you could still break those somehow if you got out of bounds

Not likely. The grass actor despawns if it can't find ground beneath it. It could be fixed by moving them up to the same level as the other ones in the room

**Comment by 3pacgangstarap** [comment]
https://youtu.be/RyT8bjuKuy0

took a couple tries but here's proof you can kill it. i think it requires biggoron sword/unbroken giant's knife, master sword jumpslash might not do enough damage to one shot it.

**Comment by rrealmuto** [comment]
You would likely not be able to get the drop from it. It takes a few frames after hitting it for it to drop.

**Comment by 3pacgangstarap** [comment]
dang, you're right. i tried for another hour to kill it with enough frames to spare that it would give up it's item and couldn't do it. i was able to hit it once with a bomb without voiding out using hover boots from the lower platform, but after that hit it disappears off the map. the enemy map tracking showed it flying off to the northeast infinitely.

anyway i did find the address for that scrub i found that wasn't shuffled
![Screenshot (2)](https://github.com/rrealmuto/OoT-Randomizer/assets/3536952/d93b3bd0-b23d-4df4-ba43-5c87d8e3b520)
I really hope I'm not being a bother, like there were reason for this exclusion as well already explain somewhere and I'm just an idiot. so far as I can tell that shouldn't be the case, but I was wrong about the bubble thing so now I'm nervous to even bring it up, lol

**Comment by rrealmuto** [comment]
so I had made an assumption that this scrub is the same as the "twenty three is number one" scrub from vanilla. That scrub isn't shuffled because it doesn't actually "drop" an item in the conventional way. Is that not the case in MQ?

**Comment by 3pacgangstarap** [comment]
nah yeah in MQ it's just a regular enemy deku scrub

**Comment by rrealmuto** [comment]
Fixed in 321aa8523c0e67f1c60033a485163d53ae973425
