### ISSUE TITLE
Issue with Detailed Logic "logic_crater_boulder_jumpslash" and "logic_crater_boulder_skip"

### ISSUE THREAD

**Issue by lamaraptor** [rrealmuto/OoT-Randomizer#94]
when creating a seed with either of these detailed logic tricks it spits out the error

> assert self.parser.events <= self.event_items, 'Parse error: undefined items %r' % (self.parser.events - self.event_items) AssertionError: Parse error: undefined items {'BOULDER TYPE.BROWN', 'BOULDER TYPE.BRONZE'}

after digging I identified the line of code causing the issue is in /data/World/Overworld.json line 2866

`((logic_crater_boulder_jumpslash or logic_crater_boulder_skip) and boulder_type('DMC_BOULDER_NEAR_FAIRY') in ['BOULDER_TYPE.BROWN', 'BOULDER_TYPE.BRONZE'] and Megaton_Hammer) or`

whatever the parser is doing there it's throwing an error, one solution that worked for me was to split the "in" check into separate "==" checks for each type,

**Comment by rrealmuto** [comment]
Should be fixed in https://github.com/OoTRandomizer/OoT-Randomizer/commit/d3d6a3147836047cf8724176116d64a09605a84f
