### ISSUE TITLE
Spirit Temple MQ incorrect logic

### ISSUE THREAD

**Issue by JustAMosquito** [rrealmuto/OoT-Randomizer#95]
Hi. I just finished my seed and found 2 incorrect logics in Spirit Temple MQ :

- _Spirit temple MQ Boulder Room Moblin_ is missing _"(Small_Key_Spirit_Temple, 7)"_. 

- This one I'm not 100% sure, but I think _Spirit Temple MQ Silver Gauntlets_ is missing _"has_soul(Iron_Knuckle)"_. And I wonder if it's not also missing "has_soul(Floormaster)" for getting _Silver Gauntlets_ and _Child Iron Knuckle_ from the _Mirror Shield Chest_ with Longshot

I hope it's clear enough for you to understand and that I could help you

**Comment by rrealmuto** [comment]
always takes me a while to figure out spirit logic and MQ makes that 10x worse. But everything you said seems right
