### ISSUE TITLE
incorrect dodongo cavern MQ logic

### ISSUE THREAD

**Issue by 3pacgangstarap** [rrealmuto/OoT-Randomizer#96]
the exit from the "Dodongos Cavern Lower Right Side" region is labeled as "Dodongos Cavern Poes Room" when i think it should be "Dodongos Cavern Lower Lizalfos"

**Comment by rrealmuto** [comment]
it's actually quite a bit more complicated than that. The exit to "Dodongos Cavern Poes Room" is intended, but is not properly accounting for souls logic.

Anyway I'm fixing it
